# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: BadBank Docker


  #push: 
    #branches:
     # - main
  jobs:
    build:
      run-on: ubuntu-latest   
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@3
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login - u $ {{ secrets.DOCKERHUB_USERNAME }}
        - name: Get the version
          id: vars
          run: echo ::set-output name=tag::$(echo ${GITHUB_ })
          name: Build the tagged Docker image
          run: docker build -t jrwtango/c2express02 
        - name: Push the tagged Docker image
          run: docker push jrwtango/c2express02


      
